### ISSUE TITLE
Data Cleaning/Manipulation

### ISSUE THREAD

**Issue by andyalex234** [andyalex234/Telecom_User_Analytics#9]
## Tasks
- [x] Fixing rows and columns
- [x] Standardizing values
- [x] Fix Invalid Values
- [x] Detect and Fix Missing Values
